"""initial schema

Revision ID: f3f282d05175
Revises: 
Create Date: 2026-05-10 20:57:38.002690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f282d05175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_entrada', sa.Time(), nullable=True),
    sa.Column('horario_saida', sa.Time(), nullable=True),
    sa.Column('tolerancia_atraso_min', sa.Integer(), nullable=True),
    sa.Column('limite_recuperacao_min', sa.Integer(), nullable=True),
    sa.Column('dias_uteis', sa.String(length=20), nullable=True),
    sa.Column('nome_empresa', sa.String(length=120), nullable=True),
    sa.Column('logo_empresa', sa.String(length=255), nullable=True),
    sa.Column('threshold_reconhecimento', sa.Float(), nullable=True),
    sa.Column('salvar_foto_captura', sa.Boolean(), nullable=True),
    sa.Column('retencao_fotos_dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('recorrente_anual', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    with op.batch_alter_table('feriados', schema=None) as batch_op:
        batch_op.create_index('ix_feriados_data', ['data'], unique=False)

    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('departamento', sa.String(length=80), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('face_encodings', sa.Text(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('usuarios_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('justificativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios_admin.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('data_hora_original', sa.DateTime(), nullable=True),
    sa.Column('editado_por_admin', sa.Boolean(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('foto_registro', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.create_index('ix_pontos_data_hora', ['data_hora'], unique=False)
        batch_op.create_index('ix_pontos_func_data', ['funcionario_id', 'data_hora'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_index('ix_pontos_func_data')
        batch_op.drop_index('ix_pontos_data_hora')

    op.drop_table('pontos')
    op.drop_table('justificativas')
    op.drop_table('audit_log')
    op.drop_table('usuarios_admin')
    op.drop_table('funcionarios')
    with op.batch_alter_table('feriados', schema=None) as batch_op:
        batch_op.drop_index('ix_feriados_data')

    op.drop_table('feriados')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
